# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021 Intel Corporation
# Copyright (c) 2023 Dell Inc, or its subsidiaries.
#

version: "3.8"
services:
  build_base:
    image: spdk
    build:
      context: build_base
    container_name: build_base

  storage-target:
    image: spdk-app
    build:
      context: spdk-app
    container_name: storage-target
    depends_on:
      - build_base
    networks:
      spdk:
        ipv4_address: 192.168.42.2
    volumes:
      - /dev/hugepages:/dev/hugepages
      - ./spdk-app/storage-target.conf:/config
    environment:
      - SPDK_HTTP_PROXY=0.0.0.0 9009 spdkuser spdkpass
    privileged: true

  telegraf:
    image: docker.io/library/telegraf:1.28
    volumes:
      - ./monitoring/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - storage-target
    networks:
      spdk:

  prometheus:
    image: docker.io/prom/prometheus:v2.47.1
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml:z
    depends_on:
      - telegraf
    networks:
      spdk:

networks:
  spdk:
    name: "spdk"
    ipam:
      config:
        - subnet: 192.168.42.0/29
          gateway: 192.168.42.1
